#!/bin/bash

#Beginning of while loop
printf "Please enter the following details\n"

#it will request the user to input an email address
printf "\nExpected format: xx@xx.xx"
printf "\nE-mail address: "
read email
#it will check what's inputted contains characters specific to an email address
#if they dont have the correct format then it will loop asking to input the correct style
until [[ $email == *?@*?.??* ]]; do
  printf "\nInvalid format: $email"
  printf "\nExpected format: xx@xx.xx"
  printf "\nPlease try again:\n"
  read email
done

#it will request the user to input a contact's name
printf "\nPlease use letters only"
printf "\nFirst Name: "
read fname
#it will check what's inputted contains only letters
#if they dont have the correct format then it will loop asking to input the correct style
until [[ $fname =~ ^[a-zA-Z]+$ ]]; do
  printf "\nInvalid format: $fname"
  printf "\nOnly letters please"
  printf "\nPlease try again:\n"
  read fname
done

#it will request the user to input a contact's name
printf "\nPlease use letters only"
printf "\nLast Name: "
read lname
#it will check what's inputted contains only letters
#if they dont have the correct format then it will loop asking to input the correct style
until [[ $lname =~ ^[a-zA-Z]+$ ]]; do
  printf "\nInvalid format: $lname"
  printf "\nOnly letters please"
  printf "\nPlease try again:\n"
  read lname
done

#Alias' can very so this is left open
printf "\nAlias: "
read alias

#addresses can hold numbers and letters so it's not neccessary to run a check
printf "\nAddress: "
read address

#this checks if the user inputs only numbers
#if they dont have the correct format then it will loop asking to input the correct style
printf "\nPlease use numbers only"
printf "\nPhone Number: "
read phone
until [[ $phone =~ ^[0-9]+$ ]]; do
  printf "\nInvalid input: $phone"
  printf "\nUse numbers only\n"
  printf "\nPlease try again:\n"
  read phone
done

#it will then take all the input data into the CustomerDetails file
printf "$email	$fname $lname	$alias	$address	$phone\n" >> CustomerDetails
printf "Customer successfully added. Returning to menu."
sleep 3

