#!/bin/bash

#the main menu that will be displayed to the user
while true; do
  clear
  printf "\n    # # # # # # # # # # # # # # # # # # # # # #"
  printf "\n    #                                         #"
  printf "\n    #     WELCOME TO THE CUSTOMER DATABASE    #"
  printf "\n    #                                         #"
  printf "\n    # # # # # # # # # # # # # # # # # # # # # #"
  printf "\n"
  printf "\n\tPlease choose one of the following:"
  printf "\n"
  printf "\n\t1) Add a new Customer"
  printf "\n\t2) Remove an existing Customer"
  printf "\n\t3) Search for a Customer"
  printf "\n\t4) E-mail a Customer"
  printf "\n\t0) Exit"
  printf "\n\t==>>"
  read option

#sential loop that will take input from the user before deciding what script file to run
  case $option in
  1)
    clear
    ./AddCust
    ;;

  2)
    clear
    ./RemCust
    ;;
  
  3)
    clear
    ./FindCust
    ;;
  
  0)
    exit
    ;;
#if the user doesn't select anything between 0-3 then if will prompt them with an invalid option message
  *)
    printf "\nInvalid input: $option"
    sleep 1
    ;;
  esac
done
