#!/bin/bash
#Beginning of while loop
while true; do
printf "\nPlease enter the customer you wish to remove"
printf "\n(type \"exit\" to return to Menu)"
printf "\n==>"

#user's input is stored
read cust

#results of a search variable is stored in here
custSearch=$(awk -v input="$cust" 'BEGIN {FS="\t"} $2 == input || $3 == input || $4 == input' CustomerDetails | awk '{print $0}')

#the number of results from the search is stored in here to be tested later
custCount=$(awk -v input="$cust" 'BEGIN {FS="\t"} $2 == input || $3 == input || $4 == input' CustomerDetails | awk 'END {print NR}')

#custCount is tested to see if there was more than one result from the search
#if so the prompt string will be set
if [[ ${custCount} > 1 ]]
  then
		prompt="Confirm multiple deletes?(y/n)"

#testing if custCount == 1 
#if so the prompt string will be set
elif [[ ${custCount} == 1 ]]
  then
		prompt="Confirm?(y/n)"

#if user types in "exit" it will return to menu
elif [[ $cust == 'exit' ]]
  then
    printf "\nReturning to Menu...\n"
    sleep 3
		break

#if the search doesn't find a match in CustomerDetails it will tell the user
#no matches found and display what they typed in
else
  printf "\nThere is no Customer by this name: $cust\n"
  continue
fi

#it will print out all the details belonging to the customer and ask the customer
#to confirm their action to delete the contact
printf "\n${custSearch}"
printf "\n${prompt}"
printf "\n==>> "
read result
#If user agrees it will make a copy of the CustomerDetails file but without the specified
#contact and then move the copy in tmp folder into the main folder
if [ "$result" == 'y' ]
	then
	grep -v "$cust" CustomerDetails > tmp/CustomerDetails
	mv tmp/CustomerDetails CustomerDetails
	printf "\nCustomer(s) Deleted. Returning to Menu...\n"
	#sleeps for 3 seconds before returning to menu
	sleep 3
else
	printf "\nReturning to start...\n"
  sleep 3
	continue
fi
break
done
